// Generated by scripts/parse.ts — do not edit
import type { KeyFile } from "../lib/types"
import key1 from "./keys/key-1.json"
import key2 from "./keys/key-2.json"

export const keysById: Record<number, KeyFile> = {
  1: key1 as KeyFile,
  2: key2 as KeyFile,
}
