import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import type { KeyFile, Paper } from "../src/lib/types"
import { parseMarkdownPaper, printVerify, SET_FILENAME_RE, setIdFromFilename } from "../src/lib/parse-paper"

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)))
const CONTENT_DIR = join(ROOT, "content")
const DATA_DIR = join(ROOT, "src/data")
const KEYS_DIR = join(ROOT, "src/server/keys")

function fail(message: string): never {
  throw new Error(message)
}

function writeBarrel(setIds: number[]): void {
  const imports = setIds.map((id) => `import paper${id} from "./paper-${id}.json"`).join("\n")
  const list = setIds.map((id) => `paper${id} as Paper`).join(", ")
  const record = setIds.map((id) => `  ${id}: paper${id} as Paper`).join(",\n")
  const source = `// Generated by scripts/parse.ts — do not edit
import type { Paper } from "../lib/types"
${imports}

export const papers: Paper[] = [${list}]

export const papersById: Record<number, Paper> = {
${record},
}

export function getPaper(setId: number): Paper | undefined {
  return papersById[setId]
}
`
  writeFileSync(join(DATA_DIR, "papers.ts"), source, "utf8")
}

function writeKeyBarrel(setIds: number[]): void {
  const imports = setIds.map((id) => `import key${id} from "./keys/key-${id}.json"`).join("\n")
  const record = setIds.map((id) => `  ${id}: key${id} as KeyFile`).join(",\n")
  const source = `// Generated by scripts/parse.ts — do not edit
import type { KeyFile } from "../lib/types"
${imports}

export const keysById: Record<number, KeyFile> = {
${record},
}
`
  writeFileSync(join(ROOT, "src/server/key-files.ts"), source, "utf8")
}

function main(): void {
  const verify = process.argv.includes("--verify")
  const files = readdirSync(CONTENT_DIR)
    .filter((name) => SET_FILENAME_RE.test(name))
    .sort((a, b) => a.localeCompare(b, "en"))

  if (files.length === 0) {
    fail(`No Markdown papers found in ${CONTENT_DIR}`)
  }

  mkdirSync(DATA_DIR, { recursive: true })
  mkdirSync(KEYS_DIR, { recursive: true })

  const setIds: number[] = []
  for (const file of files) {
    const setId = setIdFromFilename(file)
    if (setId == null) fail(`Cannot derive set id from filename "${file}"`)
    const source = readFileSync(join(CONTENT_DIR, file), "utf8")
    const { paper, key, distribution } = parseMarkdownPaper(source, setId)
    writeFileSync(join(DATA_DIR, `paper-${paper.setId}.json`), `${JSON.stringify(paper, null, 2)}\n`, "utf8")
    writeFileSync(join(KEYS_DIR, `key-${paper.setId}.json`), `${JSON.stringify(key, null, 2)}\n`, "utf8")
    setIds.push(paper.setId)
    if (verify) printVerify(paper, distribution)
  }

  writeBarrel(setIds)
  writeKeyBarrel(setIds)
  console.log(`\nWrote ${setIds.length} paper(s): ${setIds.map((id) => `paper-${id}.json`).join(", ")}`)
}

main()
