// Generated by scripts/parse.ts — do not edit
import type { Paper } from "../lib/types"
import paper1 from "./paper-1.json"
import paper2 from "./paper-2.json"

export const papers: Paper[] = [paper1 as Paper, paper2 as Paper]

export const papersById: Record<number, Paper> = {
  1: paper1 as Paper,
  2: paper2 as Paper,
}

export function getPaper(setId: number): Paper | undefined {
  return papersById[setId]
}
